version: "3.9"
services:

  redis:
    image: 'bitnami/redis:latest'
    hostname: redis
    ports:
      - '6379'
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD: my_master_password
    volumes:
      - '/path/to/redis-persistence:/bitnami'
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres2
    hostname: postgres2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped



volumes:
  postgres-data:
  pgadmin-data:
  redis:
